import AuditLog from '../models/audit-log.model.js';
import Role from '../models/role.model.js';
import User from '../models/user.model.js';
import mongoose from 'mongoose';
import { getRoleCategory } from '../utils/user.utils.js';

/**
 * Creates an audit log entry in the database.
 * @param {Object} params - Audit log parameters.
 * @param {string} params.companyId - The active tenant ID.
 * @param {string} params.userId - The acting user ID.
 * @param {string} params.module - The module name (e.g., 'user', 'role').
 * @param {string} params.action - The action being performed (e.g., 'create', 'update').
 * @param {Object} [params.oldData] - Previous state of the data.
 * @param {Object} [params.newData] - New state of the data.
 * @param {string} [params.ipAddress] - IP address of the requester.
 * @returns {Promise<Object>} The created audit log document.
 */
export const logAction = async ({
  companyId,
  userId,
  module,
  action,
  oldData = null,
  newData = null,
  ipAddress = null,
}) => {
  const auditLog = new AuditLog({
    companyId,
    userId,
    module,
    action,
    oldData,
    newData,
    ipAddress,
  });

  return await auditLog.save();
};

/**
 * Retrieves audit logs for a company with pagination and filters.
 * @param {string} companyId - The tenant ID.
 * @param {Object} [queryParams={}] - Query parameters (page, limit, userId, module, action).
 * @param {string} [requesterRole=null] - Role of the requesting user.
 * @returns {Promise<Object>} Object containing audit logs and pagination meta.
 */
export const getAuditLogs = async (companyId, queryParams = {}, requesterRole = null) => {
  const page = parseInt(queryParams.page, 10) || 1;
  const limit = parseInt(queryParams.limit, 10) || 50;
  const skip = (page - 1) * limit;

  const filter = { companyId };

  const category = getRoleCategory(requesterRole);

  // If requester is not Company Admin, exclude logs generated by Company Admin users
  if (requesterRole && category !== 'Company Admin') {
    const adminRole = await Role.findOne({ companyId, roleName: 'Company Admin' }).select('_id').lean();
    if (adminRole) {
      const adminUsers = await User.find({ companyId, roleId: adminRole._id }).select('_id').lean();
      const adminUserIds = adminUsers.map(u => u._id);
      
      if (queryParams.userId) {
        // If they filter by a user who happens to be an admin, force no results
        const isQueryingAdmin = adminUserIds.map(id => id.toString()).includes(queryParams.userId.toString());
        if (isQueryingAdmin) {
          filter.userId = new mongoose.Types.ObjectId();
        } else {
          filter.userId = queryParams.userId;
        }
      } else {
        filter.userId = { $nin: adminUserIds };
      }
    } else {
      if (queryParams.userId) filter.userId = queryParams.userId;
    }
  } else {
    if (queryParams.userId) filter.userId = queryParams.userId;
  }
  if (queryParams.module) {
    filter.module = queryParams.module;
  }
  if (queryParams.action) {
    filter.action = queryParams.action;
  }

  const total = await AuditLog.countDocuments(filter);
  const logs = await AuditLog.find(filter)
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(limit)
    .populate('userId', 'firstName lastName email');

  return {
    logs,
    pagination: {
      total,
      page,
      limit,
      pages: Math.ceil(total / limit),
    },
  };
};
